In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

In [4]:
# Name of the CSV file
file = 'Ressources/percent_of_adults_with_depression_usafacts.csv'

df = pd.read_csv(file)
df

,Years,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Percent of adults with depression (%),0.175,0.18,0.187,0.19,0.19,0.174,0.205,0.196000,0.199000,0.196000
1,By Race/Ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"American Indian or Alaskan Native, non...",NaN,NaN,NaN,NaN,0.267461538461538,0.280121212121212,0.2825625,0.263706,0.263667,0.267958
3,"Asian, non-Hispanic (%)",NaN,NaN,NaN,NaN,0.075111111111111,0.0851,0.107666666666667,0.100733,0.079778,0.097750
4,"Black, non-Hispanic (%)",0.146,0.156153846153846,0.161868421052632,0.1674,0.163512820512821,0.155054054054054,0.17355,0.175600,0.164763,0.169550
...,...,...,...,...,...,...,...,...,...,...,...
113,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179000,0.192000,0.183000
114,Sources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,Agency,Source,Table,Url,Direct Link,Updated,Update Schedule,NaN,NaN,NaN
116,NaN,Centers for Disease Control and Prevention,Behavioral Risk Factor Surveillance System,NaN,https://www.cdc.gov/brfss/brfssprevalence/,NaN,2020,NaN,NaN,NaN,NaN
117,Exported on: 11/10/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.dtypes

Years     object
2011      object
2012      object
2013      object
2014      object
2015      object
2016      object
2017      object
2018     float64
2019     float64
2020     float64
dtype: object

In [6]:
df.drop([i for i in range(1,11)],axis=0)

,Years,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Percent of adults with depression (%),0.175,0.18,0.187,0.19,0.19,0.174,0.205,0.196,0.199,0.196
11,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
12,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
13,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
14,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
...,...,...,...,...,...,...,...,...,...,...,...
113,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179,0.192,0.183
114,Sources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,Agency,Source,Table,Url,Direct Link,Updated,Update Schedule,NaN,NaN,NaN
116,NaN,Centers for Disease Control and Prevention,Behavioral Risk Factor Surveillance System,NaN,https://www.cdc.gov/brfss/brfssprevalence/,NaN,2020,NaN,NaN,NaN,NaN
117,Exported on: 11/10/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df

,Years,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Percent of adults with depression (%),0.175,0.18,0.187,0.19,0.19,0.174,0.205,0.196000,0.199000,0.196000
1,By Race/Ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"American Indian or Alaskan Native, non...",NaN,NaN,NaN,NaN,0.267461538461538,0.280121212121212,0.2825625,0.263706,0.263667,0.267958
3,"Asian, non-Hispanic (%)",NaN,NaN,NaN,NaN,0.075111111111111,0.0851,0.107666666666667,0.100733,0.079778,0.097750
4,"Black, non-Hispanic (%)",0.146,0.156153846153846,0.161868421052632,0.1674,0.163512820512821,0.155054054054054,0.17355,0.175600,0.164763,0.169550
...,...,...,...,...,...,...,...,...,...,...,...
113,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179000,0.192000,0.183000
114,Sources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,Agency,Source,Table,Url,Direct Link,Updated,Update Schedule,NaN,NaN,NaN
116,NaN,Centers for Disease Control and Prevention,Behavioral Risk Factor Surveillance System,NaN,https://www.cdc.gov/brfss/brfssprevalence/,NaN,2020,NaN,NaN,NaN,NaN
117,Exported on: 11/10/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.drop([i for i in range(1,11)],axis=0,inplace=True)

In [9]:
df

,Years,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Percent of adults with depression (%),0.175,0.18,0.187,0.19,0.19,0.174,0.205,0.196,0.199,0.196
11,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
12,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
13,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
14,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
...,...,...,...,...,...,...,...,...,...,...,...
113,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179,0.192,0.183
114,Sources:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,NaN,Agency,Source,Table,Url,Direct Link,Updated,Update Schedule,NaN,NaN,NaN
116,NaN,Centers for Disease Control and Prevention,Behavioral Risk Factor Surveillance System,NaN,https://www.cdc.gov/brfss/brfssprevalence/,NaN,2020,NaN,NaN,NaN,NaN
117,Exported on: 11/10/2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df.iloc[:-4]

,Years,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Percent of adults with depression (%),0.175,0.18,0.187,0.19,0.19,0.174,0.205,0.196,0.199,0.196
11,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
12,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
13,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
14,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
...,...,...,...,...,...,...,...,...,...,...,...
109,West Virginia (%),0.201,0.209,0.22,0.236,0.231,0.238,0.26,0.266,0.288,0.264
110,Wisconsin (%),0.148,0.161,0.181,0.17,0.175,0.167,0.188,0.196,0.205,0.198
111,Wisconsin (%),0.148,0.161,0.181,0.17,0.175,0.167,0.188,0.196,0.205,0.198
112,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179,0.192,0.183
113,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179,0.192,0.183

In [11]:
df.drop([i for i in range(114,118)],axis=0, inplace=True)

In [12]:
df

,Years,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Percent of adults with depression (%),0.175,0.18,0.187,0.19,0.19,0.174,0.205,0.196,0.199,0.196
11,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
12,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
13,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
14,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
...,...,...,...,...,...,...,...,...,...,...,...
109,West Virginia (%),0.201,0.209,0.22,0.236,0.231,0.238,0.26,0.266,0.288,0.264
110,Wisconsin (%),0.148,0.161,0.181,0.17,0.175,0.167,0.188,0.196,0.205,0.198
111,Wisconsin (%),0.148,0.161,0.181,0.17,0.175,0.167,0.188,0.196,0.205,0.198
112,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179,0.192,0.183
113,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179,0.192,0.183

In [13]:
df.to_csv("clean_data.csv", index=False)

In [14]:
df.dropna(inplace=True)

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.reset_index()

,index,Years,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,0,Percent of adults with depression (%),0.175,0.18,0.187,0.19,0.19,0.174,0.205,0.196,0.199,0.196
1,11,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.22,0.238,0.240,0.241,0.235
2,13,Alaska (%),0.165,0.169,0.163,0.156,0.16,0.142,0.185,0.202,0.174,0.159
3,15,Arizona (%),0.175,0.188,0.181,0.187,0.185,0.167,0.188,0.167,0.168,0.174
4,17,Arkansas (%),0.228,0.222,0.231,0.215,0.235,0.237,0.248,0.225,0.250,0.235
5,19,California (%),0.123,0.117,0.131,0.133,0.129,0.134,0.173,0.154,0.146,0.141
6,21,Colorado (%),0.176,0.174,0.182,0.17,0.193,0.185,0.174,0.157,0.172,0.184
7,23,Connecticut (%),0.154,0.167,0.175,0.183,0.176,0.159,0.176,0.155,0.144,0.177
8,25,Delaware (%),0.142,0.148,0.177,0.183,0.178,0.166,0.198,0.169,0.188,0.156
9,27,District of Columbia (%),0.16,0.163,0.209,0.181,0.18,0.167,0.143,0.194,0.204,0.198
10,29,Florida (%),0.165,0.169,0.168,0.162,0.165,0.142,0.171,0.156,0.177,0.147
11,31,Georgia (%),0.149,0.167,0.173,0.183,0.183,0.166,0.163,0.171,0.170,0.172
12,33,Hawaii (%),0.106,0.115,0.114,0.107,0.116,0.121,0.118,0.126,0.128,0.127
13,35,Idaho (%),0.196,0.199,0.208,0.195,0.197,0.152,0.218,0.195,0.227,0.189
14,37,Illinois (%),0.163,0.15,0.154,0.167,0.153,0.165,0.178,0.177,0.183,0.147
15,39,Indiana (%),0.208,0.195,0.195,0.207,0.204,0.159,0.235,0.197,0.210,0.219
16,41,Iowa (%),0.152,0.17,0.192,0.187,0.19,0.148,0.205,0.164,0.162,0.174
17,43,Kansas (%),0.159,0.165,0.181,0.186,0.194,0.165,0.209,0.207,0.199,0.192
18,45,Kentucky (%),0.197,0.235,0.202,0.239,0.188,0.232,0.243,0.240,0.257,0.242
19,47,Louisiana (%),0.181,0.172,0.187,0.187,0.201,0.199,0.219,0.232,0.239,0.235
20,49,Maine (%),0.244,0.227,0.234,0.237,0.24,0.211,0.26,0.228,0.235,0.221
21,51,Maryland (%),0.136,0.142,0.16,0.159,0.163,0.154,0.176,0.154,0.158,0.157
22,53,Massachusetts (%),0.167,0.189,0.197,0.217,0.209,0.187,0.184,0.181,0.185,0.179
23,55,Michigan (%),0.207,0.206,0.213,0.205,0.197,0.22,0.233,0.232,0.214,0.196
24,57,Minnesota (%),0.151,0.171,0.184,0.182,0.189,0.172,0.19,0.176,0.202,0.198
25,59,Mississippi (%),0.189,0.184,0.192,0.199,0.182,0.188,0.207,0.217,0.206,0.209
26,61,Missouri (%),0.201,0.201,0.213,0.217,0.218,0.217,0.224,0.222,0.228,0.228
27,63,Montana (%),0.205,0.2,0.211,0.204,0.199,0.194,0.212,0.219,0.241,0.226
28,65,Nebraska (%),0.169,0.168,0.182,0.177,0.176,0.178,0.194,0.173,0.162,0.168
29,67,Nevada (%),0.158,0.163,0.176,0.156,0.166,0.172,0.156,0.157,0.177,0.176
30,69,New Hampshire (%),0.218,0.197,0.221,0.21,0.209,0.221,0.23,0.207,0.200,0.214
31,73,New Mexico (%),0.204,0.199,0.195,0.211,0.202,0.183,0.212,0.172,0.174,0.176
32,75,New York (%),0.159,0.148,0.161,0.159,0.157,0.117,0.16,0.151,0.153,0.168
33,77,North Carolina (%),0.175,0.176,0.187,0.19,0.188,0.183,0.199,0.198,0.216,0.208
34,79,North Dakota (%),0.173,0.15,0.168,0.173,0.188,0.15,0.2,0.196,0.179,0.192
35,81,Ohio (%),0.177,0.189,0.202,0.209,0.196,0.174,0.226,0.200,0.203,0.220
36,83,Oklahoma (%),0.219,0.219,0.234,0.218,0.227,0.22,0.237,0.233,0.230,0.229
37,85,Oregon (%),0.239,0.234,0.266,0.24,0.267,0.25,0.241,0.262,0.246,0.212
38,87,Pennsylvania (%),0.193,0.18,0.183,0.197,0.185,0.186,0.196,0.216,0.196,0.202
39,90,Rhode Island (%),0.22,0.203,0.222,0.206,0.213,0.223,0.231,0.208,0.196,0.211
40,92,South Carolina (%),0.153,0.18,0.196,0.199,0.195,0.205,0.205,0.199,0.200,0.214
41,94,South Dakota (%),0.164,0.153,0.145,0.166,0.161,0.157,0.174,0.163,0.173,0.161
42,96,Tennessee (%),0.192,0.202,0.193,0.214,0.212,0.211,0.228,0.252,0.250,0.241
43,98,Texas (%),0.166,0.155,0.16,0.146,0.161,0.125,0.166,0.165,0.172,0.177
44,100,Utah (%),0.22,0.21,0.219,0.207,0.208,0.215,0.226,0.243,0.231,0.231
45,102,Vermont (%),0.23,0.219,0.232,0.218,0.228,0.222,0.252,0.212,0.221,0.233
46,104,Virginia (%),0.141,0.166,0.165,0.174,0.157,0.159,0.19,0.166,0.170,0.172
47,106,Washington (%),0.197,0.223,0.235,0.216,0.217,0.21,0.232,0.236,0.242,0.234
48,108,West Virginia (%),0.201,0.209,0.22,0.236,0.231,0.238,0.26,0.266,0.288,0.264
49,110,Wisconsin (%),0.148,0.161,0.181,0.17,0.175,0.167,0.188,0.196,0.205,0.198
50,112,Wyoming (%),0.19,0.18,0.187,0.19,0.209,0.155,0.212,0.179,0.192,0.183

In [17]:
df.reset_index(drop=True, inplace=True)

In [18]:
df = df.rename(columns={"Years":"State"})

In [19]:
col_change= ["2011", "2012","2013","2014","2015","2016","2017"]
df[col_change] = df[col_change].astype("float64")
df.dtypes

State     object
2011     float64
2012     float64
2013     float64
2014     float64
2015     float64
2016     float64
2017     float64
2018     float64
2019     float64
2020     float64
dtype: object

In [20]:
df.loc["2011":"2020"] = df.loc["2011":"2020"]*100
df.head()

,State,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Percent of adults with depression (%),0.175,0.180,0.187,0.190,0.190,0.174,0.205,0.196,0.199,0.196
1,Alabama (%),0.212,0.219,0.218,0.213,0.221,0.220,0.238,0.240,0.241,0.235
2,Alaska (%),0.165,0.169,0.163,0.156,0.160,0.142,0.185,0.202,0.174,0.159
3,Arizona (%),0.175,0.188,0.181,0.187,0.185,0.167,0.188,0.167,0.168,0.174
4,Arkansas (%),0.228,0.222,0.231,0.215,0.235,0.237,0.248,0.225,0.250,0.235

In [21]:
df = df.set_index("State")
df = df.iloc[1:]
df

,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
State,,,,,,,,,,
Alabama (%),0.212,0.219,0.218,0.213,0.221,0.220,0.238,0.240,0.241,0.235
Alaska (%),0.165,0.169,0.163,0.156,0.160,0.142,0.185,0.202,0.174,0.159
Arizona (%),0.175,0.188,0.181,0.187,0.185,0.167,0.188,0.167,0.168,0.174
Arkansas (%),0.228,0.222,0.231,0.215,0.235,0.237,0.248,0.225,0.250,0.235
California (%),0.123,0.117,0.131,0.133,0.129,0.134,0.173,0.154,0.146,0.141
Colorado (%),0.176,0.174,0.182,0.170,0.193,0.185,0.174,0.157,0.172,0.184
Connecticut (%),0.154,0.167,0.175,0.183,0.176,0.159,0.176,0.155,0.144,0.177
Delaware (%),0.142,0.148,0.177,0.183,0.178,0.166,0.198,0.169,0.188,0.156
District of Columbia (%),0.160,0.163,0.209,0.181,0.180,0.167,0.143,0.194,0.204,0.198
Florida (%),0.165,0.169,0.168,0.162,0.165,0.142,0.171,0.156,0.177,0.147
Georgia (%),0.149,0.167,0.173,0.183,0.183,0.166,0.163,0.171,0.170,0.172
Hawaii (%),0.106,0.115,0.114,0.107,0.116,0.121,0.118,0.126,0.128,0.127
Idaho (%),0.196,0.199,0.208,0.195,0.197,0.152,0.218,0.195,0.227,0.189
Illinois (%),0.163,0.150,0.154,0.167,0.153,0.165,0.178,0.177,0.183,0.147
Indiana (%),0.208,0.195,0.195,0.207,0.204,0.159,0.235,0.197,0.210,0.219
Iowa (%),0.152,0.170,0.192,0.187,0.190,0.148,0.205,0.164,0.162,0.174
Kansas (%),0.159,0.165,0.181,0.186,0.194,0.165,0.209,0.207,0.199,0.192
Kentucky (%),0.197,0.235,0.202,0.239,0.188,0.232,0.243,0.240,0.257,0.242
Louisiana (%),0.181,0.172,0.187,0.187,0.201,0.199,0.219,0.232,0.239,0.235
Maine (%),0.244,0.227,0.234,0.237,0.240,0.211,0.260,0.228,0.235,0.221
Maryland (%),0.136,0.142,0.160,0.159,0.163,0.154,0.176,0.154,0.158,0.157
Massachusetts (%),0.167,0.189,0.197,0.217,0.209,0.187,0.184,0.181,0.185,0.179
Michigan (%),0.207,0.206,0.213,0.205,0.197,0.220,0.233,0.232,0.214,0.196
Minnesota (%),0.151,0.171,0.184,0.182,0.189,0.172,0.190,0.176,0.202,0.198
Mississippi (%),0.189,0.184,0.192,0.199,0.182,0.188,0.207,0.217,0.206,0.209
Missouri (%),0.201,0.201,0.213,0.217,0.218,0.217,0.224,0.222,0.228,0.228
Montana (%),0.205,0.200,0.211,0.204,0.199,0.194,0.212,0.219,0.241,0.226
Nebraska (%),0.169,0.168,0.182,0.177,0.176,0.178,0.194,0.173,0.162,0.168
Nevada (%),0.158,0.163,0.176,0.156,0.166,0.172,0.156,0.157,0.177,0.176
New Hampshire (%),0.218,0.197,0.221,0.210,0.209,0.221,0.230,0.207,0.200,0.214
New Mexico (%),0.204,0.199,0.195,0.211,0.202,0.183,0.212,0.172,0.174,0.176
New York (%),0.159,0.148,0.161,0.159,0.157,0.117,0.160,0.151,0.153,0.168
North Carolina (%),0.175,0.176,0.187,0.190,0.188,0.183,0.199,0.198,0.216,0.208
North Dakota (%),0.173,0.150,0.168,0.173,0.188,0.150,0.200,0.196,0.179,0.192
Ohio (%),0.177,0.189,0.202,0.209,0.196,0.174,0.226,0.200,0.203,0.220
Oklahoma (%),0.219,0.219,0.234,0.218,0.227,0.220,0.237,0.233,0.230,0.229
Oregon (%),0.239,0.234,0.266,0.240,0.267,0.250,0.241,0.262,0.246,0.212
Pennsylvania (%),0.193,0.180,0.183,0.197,0.185,0.186,0.196,0.216,0.196,0.202
Rhode Island (%),0.220,0.203,0.222,0.206,0.213,0.223,0.231,0.208,0.196,0.211
South Carolina (%),0.153,0.180,0.196,0.199,0.195,0.205,0.205,0.199,0.200,0.214
South Dakota (%),0.164,0.153,0.145,0.166,0.161,0.157,0.174,0.163,0.173,0.161
Tennessee (%),0.192,0.202,0.193,0.214,0.212,0.211,0.228,0.252,0.250,0.241
Texas (%),0.166,0.155,0.160,0.146,0.161,0.125,0.166,0.165,0.172,0.177
Utah (%),0.220,0.210,0.219,0.207,0.208,0.215,0.226,0.243,0.231,0.231
Vermont (%),0.230,0.219,0.232,0.218,0.228,0.222,0.252,0.212,0.221,0.233
Virginia (%),0.141,0.166,0.165,0.174,0.157,0.159,0.190,0.166,0.170,0.172
Washington (%),0.197,0.223,0.235,0.216,0.217,0.210,0.232,0.236,0.242,0.234
West Virginia (%),0.201,0.209,0.220,0.236,0.231,0.238,0.260,0.266,0.288,0.264
Wisconsin (%),0.148,0.161,0.181,0.170,0.175,0.167,0.188,0.196,0.205,0.198
Wyoming (%),0.190,0.180,0.187,0.190,0.209,0.155,0.212,0.179,0.192,0.183

In [22]:
df_long = df.reset_index().melt(id_vars=['State'], var_name='Year', value_name='Depression_Percentage')

In [23]:
df_long

                         State  Year  Depression_Percentage
0                  Alabama (%)  2011                  0.212
1                   Alaska (%)  2011                  0.165
2                  Arizona (%)  2011                  0.175
3                 Arkansas (%)  2011                  0.228
4               California (%)  2011                  0.123
..                         ...   ...                    ...
495               Virginia (%)  2020                  0.172
496             Washington (%)  2020                  0.234
497          West Virginia (%)  2020                  0.264
498              Wisconsin (%)  2020                  0.198
499                Wyoming (%)  2020                  0.183

[500 rows x 3 columns]

In [24]:
df_long = df_long.set_index('State')
df_long

                           Year  Depression_Percentage
State
        Alabama (%)        2011                  0.212
        Alaska (%)         2011                  0.165
        Arizona (%)        2011                  0.175
        Arkansas (%)       2011                  0.228
        California (%)     2011                  0.123
...                         ...                    ...
        Virginia (%)       2020                  0.172
        Washington (%)     2020                  0.234
        West Virginia (%)  2020                  0.264
        Wisconsin (%)      2020                  0.198
        Wyoming (%)        2020                  0.183

[500 rows x 2 columns]

In [25]:
df_long["Depression_Percentage"] = df_long["Depression_Percentage"]*100
df_long

                           Year  Depression_Percentage
State
        Alabama (%)        2011                   21.2
        Alaska (%)         2011                   16.5
        Arizona (%)        2011                   17.5
        Arkansas (%)       2011                   22.8
        California (%)     2011                   12.3
...                         ...                    ...
        Virginia (%)       2020                   17.2
        Washington (%)     2020                   23.4
        West Virginia (%)  2020                   26.4
        Wisconsin (%)      2020                   19.8
        Wyoming (%)        2020                   18.3

[500 rows x 2 columns]

In [26]:
df_long = df_long.sort_index()
df_long

                     Year  Depression_Percentage
State
        Alabama (%)  2011                   21.2
        Alabama (%)  2018                   24.0
        Alabama (%)  2017                   23.8
        Alabama (%)  2016                   22.0
        Alabama (%)  2015                   22.1
...                   ...                    ...
        Wyoming (%)  2013                   18.7
        Wyoming (%)  2012                   18.0
        Wyoming (%)  2011                   19.0
        Wyoming (%)  2019                   19.2
        Wyoming (%)  2020                   18.3

[500 rows x 2 columns]

In [30]:
df_long.index = df_long.index.str.replace(r' \(\%\)', '', regex=True).str.replace(' ','')
df_long

         Year  Depression_Percentage
State
Alabama  2011                   21.2
Alabama  2018                   24.0
Alabama  2017                   23.8
Alabama  2016                   22.0
Alabama  2015                   22.1
...       ...                    ...
Wyoming  2013                   18.7
Wyoming  2012                   18.0
Wyoming  2011                   19.0
Wyoming  2019                   19.2
Wyoming  2020                   18.3

[500 rows x 2 columns]

In [32]:
df_long.to_csv("Ressources/State_Depression_Year.csv")

In [33]:
df_long.index

Index(['Alabama', 'Alabama', 'Alabama', 'Alabama', 'Alabama', 'Alabama',
       'Alabama', 'Alabama', 'Alabama', 'Alabama',
       ...
       'Wyoming', 'Wyoming', 'Wyoming', 'Wyoming', 'Wyoming', 'Wyoming',
       'Wyoming', 'Wyoming', 'Wyoming', 'Wyoming'],
      dtype='object', name='State', length=500)